name: run-tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json
      run: composer validate

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Setup DynamoDB
      run: docker-compose up -d dynamodb

    - name: Create DynamoDB tables
      run: make tables

    - name: Run test suite
      run: composer run-script test
